name: bytedance-piano-transcription
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.10
    - tensorflow
    - pip
    - ca-certificates
    - openssl
    - setuptools
    - wheel
    - numpy
    - scipy
    - scikit-learn
    - matplotlib
    - gcc_linux-64
    - gxx_linux-64
    - pip:
          - torch
          - audioread
          - certifi
          - cffi
          - charset-normalizer
          - cycler
          - decorator
          - fonttools
          - idna
          - importlib-metadata
          - joblib
          - kiwisolver
          - lazy-loader
          - librosa
          - llvmlite
          - mido
          - msgpack
          - numba
          - packaging
          - pillow
          - platformdirs
          - pooch
          - pycparser
          - pyparsing
          - python-dateutil
          - requests
          - six
          - soundfile
          - soxr
          - threadpoolctl
          - torchlibrosa
          - typing-extensions
          - urllib3
          - zipp
